import type { Metadata } from "next";
import { CartProvider } from "./context/CartContext";

import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Manrope } from "next/font/google";
import { ConvexClientProvider } from "./providers/ConvexClientProvider";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable}   antialiased`}>
        <ConvexClientProvider>
          <CartProvider>
            <Navbar />
            <main
              style={{ paddingTop: "var(--navbar-height)" }}
              className="pt-[88px] md:pt-24 min-h-screen "
            >
              {children}
            </main>

            <Footer />
          </CartProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
